POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjg1OTYxNDI4fQ.4-4l3SkZWz48KTOOyiWnryKQgB9GiHLKqMqtwpAvzMw